styles:
  accent:
    fg: "#66d9ef"
    bold: true
  bool-false:
    fg: "#f92672"
    bold: true
  bool-true:
    fg: "#a6e22e"
    bold: true
  detail:
    fg: "#f8f8f2"
  endpoint:
    fg: "#819aff"
    bold: true
  error:
    fg: "#f8f8f2"
    bg: "#f92672"
    bold: true
  host:
    fg: "#a6e22e"
    bold: true
  info:
    fg: "#66d9ef"
    bold: true
  notice:
    fg: "#66d9ef"
  process:
    fg: "#e6db74"
    bold: true
  repeat:
    fg: "#ae81ff"
  test-name:
    fg: "#a6e22e"
  timestamp:
    fg: "#88846f"
  warning:
    fg: "#e6db74"
    bold: true
