styles:
  accent:
    fg: cyan
  detail:
    fg: white
  error:
    fg: white
    bg: red
    bold: true
  host:
    fg: green
  info:
    fg: cyan
  notice:
    fg: cyan
  process:
    fg: orange
  repeat:
    fg: magenta
  test-name:
    fg: green
  timestamp:
    fg: gray
  warning:
    fg: yellow
